### ISSUE TITLE
SOLR doesn't index anything from my local Alfresco instance

### ISSUE THREAD

**Issue by ErmannoRusso** [zaizi/sensefy#2]
I tried to index my local Alfresco, but nothing gets indexed by Solr. I have a few documents in the Records Management site, a few others in a test site and some in the repository. On the other hand, manifold reports 182 documents. In the alfresco logs I can see the indexer working. 

In the manifold logs I have the following warnings:

[Worker thread '6'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"name":"Site Members Administrator Extension.xml","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/ae905fa9-beea-4a90-926a-470dc1c7c72e","uuid":"ae905fa9-beea-4a90-926a-470dc1c7c72e","nodeRef":"workspace://SpacesStore/ae905fa9-beea-4a90-926a-470dc1c7c72e","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '6'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"name":"Site Members Administrator Extension.xml","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/ae905fa9-beea-4a90-926a-470dc1c7c72e","uuid":"ae905fa9-beea-4a90-926a-470dc1c7c72e","nodeRef":"workspace://SpacesStore/ae905fa9-beea-4a90-926a-470dc1c7c72e","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '17'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"name":"page.component-1-1.user~admin~dashboard.xml","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/6252824a-db73-48fe-9b7e-f4b2b7a88281","uuid":"6252824a-db73-48fe-9b7e-f4b2b7a88281","nodeRef":"workspace://SpacesStore/6252824a-db73-48fe-9b7e-f4b2b7a88281","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '17'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"name":"page.component-1-1.user~admin~dashboard.xml","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/6252824a-db73-48fe-9b7e-f4b2b7a88281","uuid":"6252824a-db73-48fe-9b7e-f4b2b7a88281","nodeRef":"workspace://SpacesStore/6252824a-db73-48fe-9b7e-f4b2b7a88281","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '40'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"7009bb7c-897c-4508-8e12-81d1c7e5b2cb","nodeRef":"workspace://SpacesStore/7009bb7c-897c-4508-8e12-81d1c7e5b2cb","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '40'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"7009bb7c-897c-4508-8e12-81d1c7e5b2cb","nodeRef":"workspace://SpacesStore/7009bb7c-897c-4508-8e12-81d1c7e5b2cb","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '0'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"cfd54aad-817a-4740-935a-2f4bda53f0e6","nodeRef":"workspace://SpacesStore/cfd54aad-817a-4740-935a-2f4bda53f0e6","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '0'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"cfd54aad-817a-4740-935a-2f4bda53f0e6","nodeRef":"workspace://SpacesStore/cfd54aad-817a-4740-935a-2f4bda53f0e6","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '19'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"fba0148c-9507-408b-b332-9358720ff6cd","nodeRef":"workspace://SpacesStore/fba0148c-9507-408b-b332-9358720ff6cd","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '19'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"fba0148c-9507-408b-b332-9358720ff6cd","nodeRef":"workspace://SpacesStore/fba0148c-9507-408b-b332-9358720ff6cd","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '42'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"name":"Frozen Records","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/38c058f5-53c4-4bf1-ba51-7f57c432ec53","uuid":"38c058f5-53c4-4bf1-ba51-7f57c432ec53","nodeRef":"workspace://SpacesStore/38c058f5-53c4-4bf1-ba51-7f57c432ec53","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '42'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"name":"Frozen Records","propertiesUrl":"http://${alfresco.host}:${alfresco.port}/alfresco/service/node/details/workspace/SpacesStore/38c058f5-53c4-4bf1-ba51-7f57c432ec53","uuid":"38c058f5-53c4-4bf1-ba51-7f57c432ec53","nodeRef":"workspace://SpacesStore/38c058f5-53c4-4bf1-ba51-7f57c432ec53","type":"cm:content","deleted":false}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '0'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"a2eef5f7-75fc-47f8-b7ab-d37a05e48cc7","nodeRef":"workspace://SpacesStore/a2eef5f7-75fc-47f8-b7ab-d37a05e48cc7","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '0'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"a2eef5f7-75fc-47f8-b7ab-d37a05e48cc7","nodeRef":"workspace://SpacesStore/a2eef5f7-75fc-47f8-b7ab-d37a05e48cc7","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '40'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"b603cc62-1804-46cf-8153-963208157235","nodeRef":"workspace://SpacesStore/b603cc62-1804-46cf-8153-963208157235","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '40'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"b603cc62-1804-46cf-8153-963208157235","nodeRef":"workspace://SpacesStore/b603cc62-1804-46cf-8153-963208157235","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '19'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_txn_id is missing from document: {"docs":[{"uuid":"2e1d3c0f-fbc2-49a5-9630-952794dca1e8","nodeRef":"workspace://SpacesStore/2e1d3c0f-fbc2-49a5-9630-952794dca1e8","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}
[Worker thread '19'] WARN org.alfresco.consulting.indexer.client.WebScriptsAlfrescoClient - The key last_acl_changeset_id is missing from document: {"docs":[{"uuid":"2e1d3c0f-fbc2-49a5-9630-952794dca1e8","nodeRef":"workspace://SpacesStore/2e1d3c0f-fbc2-49a5-9630-952794dca1e8","type":"sys:deleted","deleted":true}],"store_id":"SpacesStore","store_protocol":"workspace"}

**Comment by alessio-santacroce** [comment]
Hi,
could be this one a compatibility issue?
In the setting up instructions there is no information at all about the supported Alfresco versions (community or enterprise, 4.x or 5.x)

**Comment by srojasbg** [comment]
I asked to Alessandro and it has Been tested with Alfresco 4 enterprise so
far I think. What Alfresco version are you using Ermanno?

Sent from my iPhone

On 16 Feb 2015, at 06:37, alessio-santacroce <notifications@github.com>
wrote:

Hi,
could be this one a compatibility issue?
In the setting up instructions there is no information at all about the
supported Alfresco versions (community or enterprise, 4.x or 5.x)

—
Reply to this email directly or view it on GitHub
<https://github.com/zaizi/sensefy/issues/2#issuecomment-74465552>.

-- 

------------------------------
This message should be regarded as confidential. If you have received this 
email in error please notify the sender and destroy it immediately. 
Statements of intent shall only become binding when confirmed in hard copy 
by an authorised signatory.

Zaizi Ltd is registered in England and Wales with the registration number 
6440931. The Registered Office is Brook House, 229 Shepherds Bush Road, 
London W6 7AN.

**Comment by fjalvarezb** [comment]
I spoke with Ermanno on Friday.

The reason is alfresco.host and alfresco.port attributes in alfresco-global.properties were not set. Seems like he followed this documentation properly (https://github.com/zaizi/sensefy/wiki/Setting-up-your-Sensefy-Virtual-Appliance) , but when he had to index a local Alfresco did not follow this one (https://github.com/zaizi/sensefy/wiki/Indexing-your-local-Alfresco-from-Sensefy-Virtual-Appliance).

**Comment by fjalvarezb** [comment]
About supported versions, we know it works in Alfresco Enterprise 4.2.1+ and Alfresco Community 4.2.e but we have not tested in Alfresco 5 or Alfresco 4.1 yet.

**Comment by ErmannoRusso** [comment]
My bad, I didn't realise there is another page specific for indexing local Alfresco. I will add the configuration and try again as soon as I have some spare time.

**Comment by ErmannoRusso** [comment]
I added the required properties to my local alfresco instance and it's indexing now. I use version 4.2.0.
