### ISSUE TITLE
Sensefy pre-built binary download link unavailable

### ISSUE THREAD

**Issue by jarey** [zaizi/sensefy#5]
Hi,

The link provided to download the pre-built binary of sensefy is not working (http://sensefyqa.zaizicloud.net/downloads/): 

"404 Not Found

nginx/1.6.2"

**Comment by dileepajayakody** [comment]
Hi Jarey,

You can now download the pre-built binary (sensefy.zip) from the above location.
Please share your comments after trying it out :)

Thanks,
Dileepa
