### ISSUE TITLE
[question] Is it possible to use sensefy without Alfresco?

### ISSUE THREAD

**Issue by jarey** [zaizi/sensefy#6]
We are evaluating the use of Sensefy in one of our projects at Indra, and were wondering if it's possible to use sensefy capabilities without Alfresco.

I present our use-case to be more specific:

We have a large base of documents stored in filesystem (around 285gb), mainly .pdf format, we have the content of that documents indexed in our own Lucene indexes in order to provide search capabilities.

We would like to use sensefy to improve the search experience in our site, but migrating all documentation to Alfresco is unlikely to happen.

Do you think it would be possible to use sensefy without Alfresco?

We are trying to set up a test environment with sensefy running, but are having some issues with the installation right now. 

Would be very helpful if you can answer or point us out to the right direction (we would be able to modify sensefy to our needs and collaborate to the project if you think our goal is reasonable achievable)

**Comment by dileepajayakody** [comment]
Hi Jarey,

Thank you for your interest in Sensefy.
Yes you can index documents from filesystem into a Solr index using ManifoldCF which is the document crawler used by Sensefy. 
In the ManifoldCF console you may need to map the relevant meta-data to Solr output using a Meta-data adjuster. 

For indexing documents in Sensefy you can use any repository supported by ManifoldCF, not limiting to Alfresco as a content repository.

However, the sensefy authentication service currently only support Alfresco as an authentication provider, to login to Sensefy UI. 

AuthServerApplication : https://github.com/zaizi/sensefy/blob/master/sensefy-authserver/src/main/java/org/zaizi/sensefy/auth/AuthServerApplication.java
AlfrescoLoginService in Sensefy : https://github.com/zaizi/sensefy/blob/master/sensefy-authserver/src/main/java/org/zaizi/sensefy/auth/service/AlfrescoLoginService.java

If you are using any other authentication provider for your users, you may need to modify above classes accordingly to use Sensefy Search UI.

If you got more questions, please feel free to ask.
Thanks,
Dileepa

**Comment by jarey** [comment]
Thank you very much for your answer. Will keep you informed of our progress.
