### ISSUE TITLE
Dependency problem: Unauthorised when building and running sensefy

### ISSUE THREAD

**Issue by afduarte** [zaizi/sensefy#7]
I get the following error when running `mvn clean install -Prun  -Dmaven.test.skip=true` after running `mvn clean install -Dmaven.test.skip=true` (which builds successfully)

``` sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (default-cli) on project runner: Unable to resolve artifact. Could not transfer artifact org.zaizi.sensefy:manifold-artifact:zip:2.2 from/to zaizi-community-releases (https://maven.zaizi.com/content/repositories/zaizi-community-releases): Not authorized , ReasonPhrase:Unauthorized.
[ERROR] org.zaizi.sensefy:manifold-artifact:zip:2.2
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] zaizi-community-releases (https://maven.zaizi.com/content/repositories/zaizi-community-releases, releases=true, snapshots=true),
[ERROR] spring-snapshots (http://repo.spring.io/libs-snapshot, releases=true, snapshots=true),
[ERROR] spring-snapshots-local (http://repo.spring.io/libs-snapshot-local, releases=true, snapshots=true),
[ERROR] spring-milestones (http://repo.spring.io/libs-milestone-local, releases=true, snapshots=false),
[ERROR] spring-releases (http://repo.spring.io/libs-release-local, releases=true, snapshots=false),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
```

**Comment by dileepajayakody** [comment]
Hi there,

Please note the -Prun (runner profile) is a developer profile which we use for development and testing purposes of Sensefy. It downloads manifoldcf, Solr binary artifacts to configure Sensefy. The ManifoldCF binary artifact is not available in the public maven repository, hence you get above error.

Instead of running the -Prun profile, we encourage you to build and execute Sensefy as an executable jar using below command:
mvn clean install -Pbuild-frontend,war,build-jar -Dmaven.test.skip=true

This will build the Sensefy-2.0.x jar at : /sensefy-runner/target
You can download and run ManifoldCF, Solr and Stanbol separately with Sensefy. 

Please use our develop branch when you build Sensefy as it has the latest code and documentation with ManifoldCD 2.3 and Solr 5.3 dependencies. We will further add how-to guides to build and configure ManifoldCF with Sensefy with a simple indexing job.

To run and try out Sensefy, we suggest you download the pre-configured Sensefy binary at : http://sensefyqa.zaizicloud.net/downloads/

**Comment by afduarte** [comment]
Ok thanks, that is good to know, I actually didn't want to use the preconfigured binary as I assume it is packed with a standalone version of both ManifoldCF and Stanbol, right? And I wanted to try to configure existing instances of those programs. 

I'm happy to document that and share my documentation with you afterwards if you are interested in that in case someone wants to do the same.

I will try to go through the steps you described and if it doesn't work for some reason, I'll come back here. If it works, I will jist close the issue.

Thanks for your help :)

**Comment by dileepajayakody** [comment]
Hi Antero,

You are welcome. 
Yes it is currently packaged with mcf 1.8-snaphsot and solr 4.9. 
By building sensefy developer branch you can use it with the latest mcf 2.3 and solr 5.3
Please share your experience/documentation/blog once you are done, as it will be helpful to others who wants to try out sensefy.

**Comment by afduarte** [comment]
Ok, I could only build it by changing the sensefy-runner pom.xml file.

I kept getting missing dependency problems with tomcat7-maven-plugin, so after trying several fixes I changed it to version 2.2. Do you see any problem in building and using that version instead of 2.3-SNAPSHOT?

I will edit this comment after actually building to say if everything worked as expected.

EDIT: The .jar file builds without problem, but after going through the steps described above, I now get the following error when trying to run the jar:

``` sh

java -jar sensefy-2.0.2-SNAPSHOT.jar 
Exception in thread "main" java.lang.Exception: FATAL: impossible to create directories:.extract/webapps
        at org.apache.tomcat.maven.runner.Tomcat7Runner.extract(Tomcat7Runner.java:586)
        at org.apache.tomcat.maven.runner.Tomcat7Runner.run(Tomcat7Runner.java:204)
        at org.apache.tomcat.maven.runner.Tomcat7RunnerCli.main(Tomcat7RunnerCli.java:212)

```

I don't know if this has something to do with the tomcat maven plugin version.

If I try to run the command again after the first time, I get a much longer error, but I assume that is due to the fact that the first try didn't run successfully, so I won't post it here. To confirm this, if I manually delete the .extract directory and run again, I get the first error message.

**Comment by dileepajayakody** [comment]
Hi Antero,

This is a bug with tomcat7-maven-plugin version 2.2.
You will have to use 2.3-SNAPSHOT version of the plugin.

Please follow : http://tomcat.apache.org/maven-plugin-trunk/snapshot-test.html
to add the tomcat plugin snaphot repository as a pluginRepository to sensefy-runner pom.xml
Let me know if this works for you.

**Comment by dileepajayakody** [comment]
Hi Antero,

We have added the tomcat snapshot pluginRepository to sensefy-runner/pom.xml. 
Please take an update from develop branch and it will resolve your problem

**Comment by afduarte** [comment]
Okay, I was able to build with the updated pom.xml file, although I did try that yesterday, but anyway, I must have missed something. 

Thanks. Also the addition of the external config file was helpful.

I am going to close this issue as the referred problem was solved. If I run into any other problems, I will create another issue.
